name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    env:
      PYTHONPATH: ./backend
      OPENAI_API_KEY: test_key
      AZURE_SPEECH_KEY: test_key
      ZONOS_API_KEY: test_key
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 pylint mypy
        
    - name: Run tests
      run: |
        python -m pytest tests/integration/test_api_pipeline.py -v
        
    - name: Run linting
      run: |
        echo "Running linting checks..."
        python -m flake8 app tests || true
        python -m pylint --exit-zero app tests
        python -m mypy app tests || true
        echo "Linting completed with status:"
        python -m pylint --exit-zero app tests
