name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: dummy_key
      AZURE_SPEECH_KEY: dummy_key
      ZONOS_API_KEY: dummy_key

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pylint mypy pytest-cov bandit
        
    - name: Run linting (informational)
      working-directory: ./backend
      continue-on-error: true
      run: |
        echo "Running linting checks (warnings only)..."
        flake8 app tests || echo "Flake8 found style issues"
        pylint app tests || echo "Pylint found style issues"
        mypy app tests || echo "Mypy found type issues"
        echo "Linting completed with warnings"

    - name: Run tests
      working-directory: ./backend
      run: pytest tests/integration/test_api_pipeline.py -v --cov=app --cov-report=xml
        
    - name: Run security scan
      working-directory: ./backend
      run: |
        bandit -r app/
        
    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        pytest tests/integration/test_api_pipeline.py -v --cov=app --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage
